#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
  path: /api/login_check

apprenant_liste:
    path: /api/apprenants
    methods: ['GET']
    defaults:
        _controller: App\Controller\ApprenantController::listerApprenant
        _api_resource_class: App\Entity\User
        _api_collection_operation_name: get_apprenants
        
ajouter_apprenant:
    path: /api/ajouterApprenant
    methods: ['POST']
    defaults:
        _controller: App\Controller\ApprenantController::ajouterApprenant
        _api_resource_class: App\Entity\User
        _api_collection_operation_name: post_ajouterApprenant

supprimerApprenant:
    path: /api/supprimerApprenant/{id}
    methods: ['DELETE']
    defaults:
        _controller: App\Controller\ApprenantController::supprimerApprenant
        _api_resource_class: App\Entity\User
        _api_item_operation_name: delete_supprimerApprenant
        
modifierApprenant:
    path: /api/modifierApprenant/{id}
    methods: ['PUT']
    defaults:
        _controller: App\Controller\ApprenantController::modifierApprenant
        _api_resource_class: App\Entity\User
        _api_item_operation_name: put_modifierApprenant

apprenant_liste_one:
    path: /api/apprenant/{id}
    methods: ['GET']
    defaults:
        _controller: App\Controller\ApprenantController::findApprenant
        _api_resource_class: App\Entity\User
        _api_item_operation_name: get_apprenant

formateur_liste:
    path: /api/formateurs
    methods: ['GET']
    defaults:
        _controller: App\Controller\FormateurController::listerFormateur
        _api_resource_class: App\Entity\User
        _api_collection_operation_name: get_formateurs
        
formateur_liste_one:
    path: /api/formateur/{id}
    methods: ['GET']
    defaults:
        _controller: App\Controller\FormateurController::findFormateur
        _api_resource_class: App\Entity\User
        _api_item_operation_name: get_formateur

modifierFormateur:
    path: /api/modifierFormateur/{id}
    methods: ['PUT']
    defaults:
        _controller: App\Controller\FormateurController::modifierFormateur
        _api_resource_class: App\Entity\User
        _api_item_operation_name: put_modifierFormateur